# Generated by Django 5.2.7 on 2026-04-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_our_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactenquiry',
            name='type',
            field=models.CharField(blank=True, choices=[('requirement', 'Real Estate Requirement'), ('owner', 'Property Owner'), ('partner', 'Channel Partner'), ('job', 'Job Inquiry'), ('complaint', 'Complaint'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
