# Generated by Django 5.2.7 on 2026-04-07 05:00

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_contactenquiry_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hero_Title', models.CharField(max_length=200)),
                ('Hero_Subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('Hero_Image', models.ImageField(blank=True, null=True, upload_to='about/hero/')),
                ('Title', models.CharField(max_length=200)),
                ('Subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('Description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('Mission_Title', models.CharField(blank=True, max_length=200, null=True)),
                ('Mission_Description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('Vision_Title', models.CharField(blank=True, max_length=200, null=True)),
                ('Vision_Description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '2. About Page',
            },
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
