# Generated by Django 5.2.7 on 2026-04-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_about_us_delete_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Toggle visibility on frontend'),
        ),
    ]
