# Generated by Django 5.2.7 on 2026-04-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_about_us_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, help_text='Toggle visibility on frontend', null=True),
        ),
    ]
