# Generated by Django 5.2.7 on 2026-04-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_about_us_created_at_alter_about_us_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards_Recognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='awards/')),
                ('order', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'verbose_name_plural': '8. Awards & Recognition',
                'ordering': ['order'],
            },
        ),
    ]
